Macluckiestorytelling
WildCodeSchool/bordeaux-0218-php-digitalagency pull request #10
Opened 2018-04-25 14:55 UTC by macluckie

hello 
le story telling est intégré avec sa page admin

2018-04-25 15:15 UTC, AurelienBarbier commented on app/routing.php
> +    ['adminstorytelling', '/adminstorytelling',['GET','POST']]
camelCase !

2018-04-25 15:17 UTC, AurelienBarbier requested changes

2018-04-25 15:17 UTC, AurelienBarbier commented on src/View/layout.html.twig
> +      <li><a href="http://localhost:8000/storytelling"><span>L'équipe</span></a></li>
J’avais pas vu précédemment, mais, si demain on lace le localhost sur le port 8010, mes url ne sont plus valide.

2018-04-25 15:17 UTC, AurelienBarbier commented on src/View/tetraDigital/story.html.twig
> +<p>toto</p>
Toto va à la wild code school ?

2018-04-25 15:46 UTC, macluckie commented
modifcation effectué sauf pour les liens  je cherche comment faire

2018-04-26 13:29 UTC, AurelienBarbier requested changes
Allez, je vais être exigeant sur celle-ci : 
- L'indentation est elle bonne ?
- Est ce que PHP Codesniffer a été lancé ?

2018-04-27 08:53 UTC, AurelienBarbier approved these changes

2018-04-27 08:53 UTC, merged