css contact
WildCodeSchool/bordeaux-0218-php-digitalagency pull request #12
Opened 2018-05-02 13:50 UTC by Discamps

2018-05-02 14:14 UTC, AurelienBarbier requested changes

2018-05-02 14:14 UTC, AurelienBarbier commented on src/View/tetraDigital/contact.html.twig
> +<!-- <form method="post">
Pas de code mort !

2018-05-02 14:14 UTC, AurelienBarbier commented on src/View/tetraDigital/story.html.twig
> +<p>vero</p>
C'est voulu que le story telling soit "vero" ?

2018-05-02 14:52 UTC, Discamps commented on src/View/tetraDigital/story.html.twig
> +<p>vero</p>
Non étant donné qu'il s'agit d'une partie administrable par les users, j'avais fait un essai

2018-05-03 11:56 UTC, AurelienBarbier requested changes

2018-05-03 11:56 UTC, AurelienBarbier commented on src/View/tetraDigital/contact.html.twig
> +<!-- <form method="post">
J'ai encore du code mort ici

2018-05-03 13:33 UTC, AurelienBarbier approved these changes

2018-05-03 15:49 UTC, AurelienBarbier approved these changes

2018-05-03 15:49 UTC, merged