Macluckiestorytelling
WildCodeSchool/bordeaux-0218-php-digitalagency pull request #13
Opened 2018-05-02 15:21 UTC by macluckie

css appliquer
et mise en page

2018-05-02 15:41 UTC, AurelienBarbier requested changes

2018-05-02 15:41 UTC, AurelienBarbier commented on src/View/tetraDigital/index.html.twig
> +<!--
code mort

2018-05-02 20:35 UTC, macluckie commented on src/View/tetraDigital/index.html.twig
> +<!--
code supprimé
+ajout de nouvelle modification dans mon push 
(portfolioController et portfolioManager)

2018-05-03 12:03 UTC, macluckie reviewed
pas de conflit

2018-05-03 12:04 UTC, macluckie commented
pas de  conflit

2018-05-03 13:02 UTC, macluckie commented
conflit resolu

2018-05-03 13:35 UTC, AurelienBarbier requested changes

2018-05-03 13:35 UTC, AurelienBarbier commented on public/assets/css/changeportfolio.css
> +=======
Y a encore des conflits

2018-05-03 14:54 UTC, AurelienBarbier approved these changes

2018-05-03 15:19 UTC, merged